import subprocess
#
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o Adam', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o Adadelta', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o Nadam', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o RMSprop', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o SGD', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o Adamax', shell=True)
# subprocess.call('python resnet200.py -i data/48/2class -d 48 -e 1 -b 8 -o Adagrad', shell=True)

# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op Adam', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op Adadelta', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op Nadam', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op RMSprop', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op SGD', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op Adamax', shell=True)
# subprocess.call('python resnet182.py -i dataset/10 -d 200 -e 1 -b 8 -op Adagrad', shell=True)

# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o Adam', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o Adadelta', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o Nadam', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o RMSprop', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o SGD', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o Adamax', shell=True)
# subprocess.call('python resnet212.py -i data/48/2class -d 48 -e 1 -b 8 -o Adagrad', shell=True)

# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o Adam', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o Adadelta', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o Nadam', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o RMSprop', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o SGD', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o Adamax', shell=True)
# subprocess.call('python resnet152.py -i data/48/2class -d 48 -e 1 -b 8 -o Adagrad', shell=True)

subprocess.call('python vgg16.py', shell=True)
subprocess.call('python vgg19.py', shell=True)
subprocess.call('python resnet50_weight.py', shell=True)
subprocess.call('python InceptionResnetV2.py', shell=True)
subprocess.call('python InceptionV3.py', shell=True)
subprocess.call('python MobileNet.py', shell=True)
subprocess.call('python Xception.py', shell=True)
